### ISSUE TITLE
options iteration. 

### ISSUE THREAD

**Issue by cloudnull** [mwhahaha/tripleo-operator-ansible#1]
One nit: I think https://github.com/mwhahaha/tripleo-operator-ansible/blob/5ba8c48021d2db64b77c3b959a85cf225ffd5d7f/tripleo/operator/plugins/modules/timestamp_file.py#L84 needs to be `options.items():`? I believe in py2 that would unpack as a list of tuples, in py3 that would return a generator. Maybe that's not needed anymore?

**Comment by mwhahaha** [comment]
Yea it needs a .items()
