### ISSUE TITLE
using booleans in ansible

### ISSUE THREAD

**Issue by cloudnull** [mwhahaha/tripleo-operator-ansible#2]
Ansible uses a internal special Boolean function which converts a collections of strings and objects to a proper Boolean operator. 

``` python
from ansible.module_utils.parsing.convert_bool import boolean
```

We may need to import and change this line https://github.com/mwhahaha/tripleo-operator-ansible/blob/a997a79ac7e5a2cb48c5fd5b834e62466feb3d9c/tripleo/operator/plugins/action/timestamp_file.py#L151 to using the ansible built-in to ensure that if a user passes in something like "yes", "no", "true", or "false" we get the proper `True` or `False` value.

something like 

``` python
        if boolean(args.get('remove', False), strict=False):
            # cleanup original file as requested
            file_result = self._execute_module(
                module_name='file',
                module_args=dict(path=src_path, state='absent'),
                task_vars=task_vars
            )
```

**Comment by mwhahaha** [comment]
This has been updated
