### ISSUE TITLE
module should reflect "changed" if file is removed

### ISSUE THREAD

**Issue by cloudnull** [mwhahaha/tripleo-operator-ansible#3]
the object `file_result` is not used https://github.com/mwhahaha/tripleo-operator-ansible/blob/a997a79ac7e5a2cb48c5fd5b834e62466feb3d9c/tripleo/operator/plugins/action/timestamp_file.py#L153

We may be able to use the results in this object to help inform a `changed` state.

**Comment by mwhahaha** [comment]
I'm now using this if it fails, we return the failure result. Changed is true if we make a copy, the removal failures should impact the overall action however.
